// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/mongocli/internal/store (interfaces: VersionDescriber)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVersionDescriber is a mock of VersionDescriber interface.
type MockVersionDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockVersionDescriberMockRecorder
}

// MockVersionDescriberMockRecorder is the mock recorder for MockVersionDescriber.
type MockVersionDescriberMockRecorder struct {
	mock *MockVersionDescriber
}

// NewMockVersionDescriber creates a new mock instance.
func NewMockVersionDescriber(ctrl *gomock.Controller) *MockVersionDescriber {
	mock := &MockVersionDescriber{ctrl: ctrl}
	mock.recorder = &MockVersionDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionDescriber) EXPECT() *MockVersionDescriberMockRecorder {
	return m.recorder
}

// LatestVersion mocks base method.
func (m *MockVersionDescriber) LatestVersion() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestVersion indicates an expected call of LatestVersion.
func (mr *MockVersionDescriberMockRecorder) LatestVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersion", reflect.TypeOf((*MockVersionDescriber)(nil).LatestVersion))
}
