// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/mongocli/internal/store (interfaces: PrivateEndpointLister,PrivateEndpointDescriber,PrivateEndpointCreator,PrivateEndpointDeleter)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	mongodbatlas "go.mongodb.org/atlas/mongodbatlas"
	reflect "reflect"
)

// MockPrivateEndpointLister is a mock of PrivateEndpointLister interface
type MockPrivateEndpointLister struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateEndpointListerMockRecorder
}

// MockPrivateEndpointListerMockRecorder is the mock recorder for MockPrivateEndpointLister
type MockPrivateEndpointListerMockRecorder struct {
	mock *MockPrivateEndpointLister
}

// NewMockPrivateEndpointLister creates a new mock instance
func NewMockPrivateEndpointLister(ctrl *gomock.Controller) *MockPrivateEndpointLister {
	mock := &MockPrivateEndpointLister{ctrl: ctrl}
	mock.recorder = &MockPrivateEndpointListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrivateEndpointLister) EXPECT() *MockPrivateEndpointListerMockRecorder {
	return m.recorder
}

// PrivateEndpoints mocks base method
func (m *MockPrivateEndpointLister) PrivateEndpoints(arg0 string, arg1 *mongodbatlas.ListOptions) ([]mongodbatlas.PrivateEndpointConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateEndpoints", arg0, arg1)
	ret0, _ := ret[0].([]mongodbatlas.PrivateEndpointConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateEndpoints indicates an expected call of PrivateEndpoints
func (mr *MockPrivateEndpointListerMockRecorder) PrivateEndpoints(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateEndpoints", reflect.TypeOf((*MockPrivateEndpointLister)(nil).PrivateEndpoints), arg0, arg1)
}

// MockPrivateEndpointDescriber is a mock of PrivateEndpointDescriber interface
type MockPrivateEndpointDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateEndpointDescriberMockRecorder
}

// MockPrivateEndpointDescriberMockRecorder is the mock recorder for MockPrivateEndpointDescriber
type MockPrivateEndpointDescriberMockRecorder struct {
	mock *MockPrivateEndpointDescriber
}

// NewMockPrivateEndpointDescriber creates a new mock instance
func NewMockPrivateEndpointDescriber(ctrl *gomock.Controller) *MockPrivateEndpointDescriber {
	mock := &MockPrivateEndpointDescriber{ctrl: ctrl}
	mock.recorder = &MockPrivateEndpointDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrivateEndpointDescriber) EXPECT() *MockPrivateEndpointDescriberMockRecorder {
	return m.recorder
}

// PrivateEndpoint mocks base method
func (m *MockPrivateEndpointDescriber) PrivateEndpoint(arg0, arg1 string) (*mongodbatlas.PrivateEndpointConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*mongodbatlas.PrivateEndpointConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateEndpoint indicates an expected call of PrivateEndpoint
func (mr *MockPrivateEndpointDescriberMockRecorder) PrivateEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateEndpoint", reflect.TypeOf((*MockPrivateEndpointDescriber)(nil).PrivateEndpoint), arg0, arg1)
}

// MockPrivateEndpointCreator is a mock of PrivateEndpointCreator interface
type MockPrivateEndpointCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateEndpointCreatorMockRecorder
}

// MockPrivateEndpointCreatorMockRecorder is the mock recorder for MockPrivateEndpointCreator
type MockPrivateEndpointCreatorMockRecorder struct {
	mock *MockPrivateEndpointCreator
}

// NewMockPrivateEndpointCreator creates a new mock instance
func NewMockPrivateEndpointCreator(ctrl *gomock.Controller) *MockPrivateEndpointCreator {
	mock := &MockPrivateEndpointCreator{ctrl: ctrl}
	mock.recorder = &MockPrivateEndpointCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrivateEndpointCreator) EXPECT() *MockPrivateEndpointCreatorMockRecorder {
	return m.recorder
}

// CreatePrivateEndpoint mocks base method
func (m *MockPrivateEndpointCreator) CreatePrivateEndpoint(arg0 string, arg1 *mongodbatlas.PrivateEndpointConnection) (*mongodbatlas.PrivateEndpointConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*mongodbatlas.PrivateEndpointConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateEndpoint indicates an expected call of CreatePrivateEndpoint
func (mr *MockPrivateEndpointCreatorMockRecorder) CreatePrivateEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateEndpoint", reflect.TypeOf((*MockPrivateEndpointCreator)(nil).CreatePrivateEndpoint), arg0, arg1)
}

// MockPrivateEndpointDeleter is a mock of PrivateEndpointDeleter interface
type MockPrivateEndpointDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateEndpointDeleterMockRecorder
}

// MockPrivateEndpointDeleterMockRecorder is the mock recorder for MockPrivateEndpointDeleter
type MockPrivateEndpointDeleterMockRecorder struct {
	mock *MockPrivateEndpointDeleter
}

// NewMockPrivateEndpointDeleter creates a new mock instance
func NewMockPrivateEndpointDeleter(ctrl *gomock.Controller) *MockPrivateEndpointDeleter {
	mock := &MockPrivateEndpointDeleter{ctrl: ctrl}
	mock.recorder = &MockPrivateEndpointDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrivateEndpointDeleter) EXPECT() *MockPrivateEndpointDeleterMockRecorder {
	return m.recorder
}

// DeletePrivateEndpoint mocks base method
func (m *MockPrivateEndpointDeleter) DeletePrivateEndpoint(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateEndpoint", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateEndpoint indicates an expected call of DeletePrivateEndpoint
func (mr *MockPrivateEndpointDeleterMockRecorder) DeletePrivateEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateEndpoint", reflect.TypeOf((*MockPrivateEndpointDeleter)(nil).DeletePrivateEndpoint), arg0, arg1)
}
