#!/usr/bin/env bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

for FILE in ${STAGED_GO_FILES}
do
    gofmt -w -s ${FILE}
    goimports -w ${FILE}
done

if [[ -n "${STAGED_GO_FILES}" ]]; then
    go test -race ./internal...
    make fix-lint
fi

STAGED_EVG_FILES=$(git diff --cached --name-only | grep "evergreen.yml$")

for FILE in ${STAGED_EVG_FILES}
do
    evergreen validate ${FILE}
done
