version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 10
    reviewers:
      - "mongodb/apix-2"
    ignore:
      - dependency-name: "go.mongodb.org/atlas-sdk/*"
    groups:
      golang:
        patterns:
          - "golang.org*"
      cloud-providers:
        patterns:
          - "*google.golang.org*"
          - "github.com/aws*"
          - "github.com/Azure*"
      containers:
        patterns:
          - "github.com/containers*"
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: tuesday
    reviewers:
      - "mongodb/apix-devtools"
    groups:
      docker:
        patterns:
          - "docker*"
