version: 1
issues: True
labels:
  - label: "kubernetes"
    type: "issue"
    body: "kubernetes*"
  - label: "need-doc-review"
    type: "pull_request"
    draft: False
    files:
      - "docs/command/*.txt"
  - label: "mongocli"
    type: "pull_request"
    draft: False
    base-branch: mongocli-master
  - label: "atlascli"
    type: "pull_request"
    base-branch: master
