---
kind: pipeline
type: docker
name: mongocli

platform:
  os: linux
  arch: amd64

steps:
  - name: dependencies
    image: golang:1.13
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install -g snyk
      - snyk test --org=cloud
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    when:
      branch:
        - master
      event:
        - push

  - name: test
    image: golang:1.13
    commands:
      - make test
    volumes:
      - name: deps
        path: /go

  - name: lint
    image: golangci/golangci-lint:v1.23.6
    commands:
      - make lint

  - name: e2e
    image: golang:1.13
    commands:
      - make e2e-test
    environment:
      MCLI_OPS_MANAGER_URL:
        from_secret: mcli_ops_manager_url
      MCLI_ORG_ID:
        from_secret: mcli_org_id
      MCLI_PRIVATE_API_KEY:
        from_secret: mcli_private_api_key
      MCLI_PROJECT_ID:
        from_secret: mcli_project_id
      MCLI_PUBLIC_API_KEY:
        from_secret: mcli_public_api_key
      MCLI_SERVICE:
        from_secret: mcli_service
    volumes:
      - name: deps
        path: /go
    depends_on:
      - test
      - lint

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
