---
kind: pipeline
type: docker
name: mongocli

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.14
    commands:
      - make test
    volumes:
      - name: deps
        path: /go

  - name: lint
    image: golangci/golangci-lint:v1.30.0
    commands:
      - make lint

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
