---
kind: pipeline
type: docker
name: mcli

steps:
  - name: test
    image: golang:1.13
    volumes:
      - name: deps
        path: /go
    commands:
      - make test
  - name: lint
    image: golangci/golangci-lint:v1.23.3
    commands:
      - make lint
  - name: build
    image: golang:1.13
    volumes:
      - name: deps
        path: /go
    commands:
      - make build

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
