---
kind: pipeline
name: mcli
type: docker

steps:
  - name: test
    image: golang:1.13
    volumes:
      - name: deps
        path: /go
    commands:
      - make test

  - name: lint
    image: golangci/golangci-lint:v1.22.0
    commands:
      - make lint

  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go build
volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
