---
kind: pipeline
type: docker
name: mongocli

platform:
  os: linux
  arch: amd64

steps:
  - name: dependencies
    image: golang:1.14
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install -g snyk
      - snyk test --org=cloud
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    when:
      branch:
        - master
      event:
        - push

  - name: test
    image: golang:1.14
    commands:
      - make test
    volumes:
      - name: deps
        path: /go

  - name: lint
    image: golangci/golangci-lint:v1.26.0
    commands:
      - make lint

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
