linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - octalLiteral
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot # Check if comments end in a period [fast: true, auto-fix: true]
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - predeclared
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - asciicheck
  # - dupl
  # - funlen
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - goerr113
  # - lll
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl

run:
  tests: true
  build-tags:
    - e2e
    - unit
    - integration
  skip-dirs:
    - internal/mocks
  modules-download-mode: readonly

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: e2e # Don't check for cyclomatic complexity on e2e file.
      linters:
        - gocyclo
    - path: internal/test/fixture # Don't check for magic numbers on fixtures.
      linters:
        - gomnd
