before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/mongodb/mongocli/internal/version.Version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: macos
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - LICENSE
    - third_party_notices/**/*
brews:
- name: mongocli
  github:
    owner: mongodb-labs
    name: homebrew-mongocli
  url_template: "https://github.com/mongodb/mongocli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
    name: gustavo.bazan
    email: gustavo.bazan@mongodb.com
  homepage: "https://github.com/mongodb/mongocli"
  description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  skip_upload: true
  test: |
    system "#{bin}/mongocli --version"
  install: |
    bin.install "mongocli"
nfpms:
  - id: mongocli
    package_name: mongocli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64
    vendor: MongoDB Inc.
    homepage: https://www.mongodb.com/
    maintainer: MongoDB Inc. <support@mongodb.com>
    description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
    license: Apache 2.0
    formats:
      - deb
      - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "next"
release:
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
