before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/mongodb/mongocli/internal/version.Version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: macos
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - LICENSE
    - third_party_notices/**/*
brews:
- name: mongocli
  github:
    owner: mongodb-labs
    name: homebrew-mongocli
  url_template: "https://github.com/mongodb/mongocli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
    name: gustavo.bazan
    email: gustavo.bazan@mongodb.com
  homepage: "https://github.com/mongodb/mongocli"
  description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  skip_upload: true
  test: |
    system "#{bin}/mongocli --version"
  install: |
    bin.install "mongocli"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}_latest"
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
