before:
  hooks:
    - go mod tidy

release:
  draft: true
  prerelease: auto

builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/mongodb/mongocli/internal/version.Version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: macos
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - LICENSE
    - third_party_notices/**/*
brews:
- name: mongocli
  github:
    owner: mongodb
    name: homebrew-brew
  skip_upload: auto
  description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  homepage: https://github.com/mongodb/mongocli
  url_template: https://github.com/mongodb/mongocli/releases/download/{{ .Tag }}/{{ .ArtifactName }}
  install: |
    bin.install "mongocli"
  test: |
    system "#{bin}/mongocli --version"
nfpms:
- package_name: mongocli
  vendor: MongoDB Inc.
  homepage: https://www.mongodb.com/
  maintainer: MongoDB Inc. <support@mongodb.com>
  description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  license: Apache 2.0
  bindir: /usr/bin
  formats:
    - deb
    - rpm
  replacements:
    amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: next
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
