// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/mongodb-atlas-cli/atlascli/internal/cli/organizations/apikeys (interfaces: OrganizationAPIKeyDeleter)
//
// Generated by this command:
//
//	mockgen -typed -destination=delete_mock_test.go -package=apikeys . OrganizationAPIKeyDeleter
//

// Package apikeys is a generated GoMock package.
package apikeys

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationAPIKeyDeleter is a mock of OrganizationAPIKeyDeleter interface.
type MockOrganizationAPIKeyDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationAPIKeyDeleterMockRecorder
	isgomock struct{}
}

// MockOrganizationAPIKeyDeleterMockRecorder is the mock recorder for MockOrganizationAPIKeyDeleter.
type MockOrganizationAPIKeyDeleterMockRecorder struct {
	mock *MockOrganizationAPIKeyDeleter
}

// NewMockOrganizationAPIKeyDeleter creates a new mock instance.
func NewMockOrganizationAPIKeyDeleter(ctrl *gomock.Controller) *MockOrganizationAPIKeyDeleter {
	mock := &MockOrganizationAPIKeyDeleter{ctrl: ctrl}
	mock.recorder = &MockOrganizationAPIKeyDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationAPIKeyDeleter) EXPECT() *MockOrganizationAPIKeyDeleterMockRecorder {
	return m.recorder
}

// DeleteOrganizationAPIKey mocks base method.
func (m *MockOrganizationAPIKeyDeleter) DeleteOrganizationAPIKey(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganizationAPIKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganizationAPIKey indicates an expected call of DeleteOrganizationAPIKey.
func (mr *MockOrganizationAPIKeyDeleterMockRecorder) DeleteOrganizationAPIKey(arg0, arg1 any) *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationAPIKey", reflect.TypeOf((*MockOrganizationAPIKeyDeleter)(nil).DeleteOrganizationAPIKey), arg0, arg1)
	return &MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall{Call: call}
}

// MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall wrap *gomock.Call
type MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall) Return(arg0 error) *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall) Do(f func(string, string) error) *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall) DoAndReturn(f func(string, string) error) *MockOrganizationAPIKeyDeleterDeleteOrganizationAPIKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
