// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/mongodb-atlas-cli/atlascli/internal/cli/search/nodes (interfaces: SearchNodesCreator)
//
// Generated by this command:
//
//	mockgen -typed -destination=create_mock_test.go -package=nodes . SearchNodesCreator
//

// Package nodes is a generated GoMock package.
package nodes

import (
	reflect "reflect"

	admin "go.mongodb.org/atlas-sdk/v20250312002/admin"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchNodesCreator is a mock of SearchNodesCreator interface.
type MockSearchNodesCreator struct {
	ctrl     *gomock.Controller
	recorder *MockSearchNodesCreatorMockRecorder
	isgomock struct{}
}

// MockSearchNodesCreatorMockRecorder is the mock recorder for MockSearchNodesCreator.
type MockSearchNodesCreatorMockRecorder struct {
	mock *MockSearchNodesCreator
}

// NewMockSearchNodesCreator creates a new mock instance.
func NewMockSearchNodesCreator(ctrl *gomock.Controller) *MockSearchNodesCreator {
	mock := &MockSearchNodesCreator{ctrl: ctrl}
	mock.recorder = &MockSearchNodesCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchNodesCreator) EXPECT() *MockSearchNodesCreatorMockRecorder {
	return m.recorder
}

// CreateSearchNodes mocks base method.
func (m *MockSearchNodesCreator) CreateSearchNodes(arg0, arg1 string, arg2 *admin.ApiSearchDeploymentRequest) (*admin.ApiSearchDeploymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSearchNodes", arg0, arg1, arg2)
	ret0, _ := ret[0].(*admin.ApiSearchDeploymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSearchNodes indicates an expected call of CreateSearchNodes.
func (mr *MockSearchNodesCreatorMockRecorder) CreateSearchNodes(arg0, arg1, arg2 any) *MockSearchNodesCreatorCreateSearchNodesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSearchNodes", reflect.TypeOf((*MockSearchNodesCreator)(nil).CreateSearchNodes), arg0, arg1, arg2)
	return &MockSearchNodesCreatorCreateSearchNodesCall{Call: call}
}

// MockSearchNodesCreatorCreateSearchNodesCall wrap *gomock.Call
type MockSearchNodesCreatorCreateSearchNodesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSearchNodesCreatorCreateSearchNodesCall) Return(arg0 *admin.ApiSearchDeploymentResponse, arg1 error) *MockSearchNodesCreatorCreateSearchNodesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSearchNodesCreatorCreateSearchNodesCall) Do(f func(string, string, *admin.ApiSearchDeploymentRequest) (*admin.ApiSearchDeploymentResponse, error)) *MockSearchNodesCreatorCreateSearchNodesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSearchNodesCreatorCreateSearchNodesCall) DoAndReturn(f func(string, string, *admin.ApiSearchDeploymentRequest) (*admin.ApiSearchDeploymentResponse, error)) *MockSearchNodesCreatorCreateSearchNodesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SearchNodes mocks base method.
func (m *MockSearchNodesCreator) SearchNodes(arg0, arg1 string) (*admin.ApiSearchDeploymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNodes", arg0, arg1)
	ret0, _ := ret[0].(*admin.ApiSearchDeploymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNodes indicates an expected call of SearchNodes.
func (mr *MockSearchNodesCreatorMockRecorder) SearchNodes(arg0, arg1 any) *MockSearchNodesCreatorSearchNodesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNodes", reflect.TypeOf((*MockSearchNodesCreator)(nil).SearchNodes), arg0, arg1)
	return &MockSearchNodesCreatorSearchNodesCall{Call: call}
}

// MockSearchNodesCreatorSearchNodesCall wrap *gomock.Call
type MockSearchNodesCreatorSearchNodesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSearchNodesCreatorSearchNodesCall) Return(arg0 *admin.ApiSearchDeploymentResponse, arg1 error) *MockSearchNodesCreatorSearchNodesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSearchNodesCreatorSearchNodesCall) Do(f func(string, string) (*admin.ApiSearchDeploymentResponse, error)) *MockSearchNodesCreatorSearchNodesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSearchNodesCreatorSearchNodesCall) DoAndReturn(f func(string, string) (*admin.ApiSearchDeploymentResponse, error)) *MockSearchNodesCreatorSearchNodesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
