// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/mongodb-atlas-cli/atlascli/internal/cli/backup/schedule (interfaces: Describer)
//
// Generated by this command:
//
//	mockgen -typed -destination=describe_mock_test.go -package=schedule . Describer
//

// Package schedule is a generated GoMock package.
package schedule

import (
	reflect "reflect"

	admin "go.mongodb.org/atlas-sdk/v20240530005/admin"
	gomock "go.uber.org/mock/gomock"
)

// MockDescriber is a mock of Describer interface.
type MockDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockDescriberMockRecorder
	isgomock struct{}
}

// MockDescriberMockRecorder is the mock recorder for MockDescriber.
type MockDescriberMockRecorder struct {
	mock *MockDescriber
}

// NewMockDescriber creates a new mock instance.
func NewMockDescriber(ctrl *gomock.Controller) *MockDescriber {
	mock := &MockDescriber{ctrl: ctrl}
	mock.recorder = &MockDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDescriber) EXPECT() *MockDescriberMockRecorder {
	return m.recorder
}

// DescribeSchedule mocks base method.
func (m *MockDescriber) DescribeSchedule(arg0, arg1 string) (*admin.DiskBackupSnapshotSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeSchedule", arg0, arg1)
	ret0, _ := ret[0].(*admin.DiskBackupSnapshotSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeSchedule indicates an expected call of DescribeSchedule.
func (mr *MockDescriberMockRecorder) DescribeSchedule(arg0, arg1 any) *MockDescriberDescribeScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSchedule", reflect.TypeOf((*MockDescriber)(nil).DescribeSchedule), arg0, arg1)
	return &MockDescriberDescribeScheduleCall{Call: call}
}

// MockDescriberDescribeScheduleCall wrap *gomock.Call
type MockDescriberDescribeScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDescriberDescribeScheduleCall) Return(arg0 *admin.DiskBackupSnapshotSchedule, arg1 error) *MockDescriberDescribeScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDescriberDescribeScheduleCall) Do(f func(string, string) (*admin.DiskBackupSnapshotSchedule, error)) *MockDescriberDescribeScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDescriberDescribeScheduleCall) DoAndReturn(f func(string, string) (*admin.DiskBackupSnapshotSchedule, error)) *MockDescriberDescribeScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
