[package]
name = "atlas-cli-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
heck = { workspace = true }
models = { path = "../models" }
openapiv3 = { workspace = true }
openapiv3-resolve = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde_yaml = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1.44"

[dev-dependencies]
insta = { workspace = true, features = ["json"] }
prettyplease = "0.2"
