[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { path = "../models" }
openapiv3-resolve = { workspace = true }
nutype = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
insta = { workspace = true, features = ["json"] }
serde_yaml = { workspace = true }
