name: Detect Breaking Changes

on:
  pull_request:

jobs:
  breaking-changes-manifest:
    name: Generate Breaking Changes Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod download
      - name: Run breaking changes validator
        run: |
          set -e
          go run ./tools/cmd/breakvalidator generate > main.json
      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: breaking-changes-manifest
          path: main.json
  detect-breaking-changes:
    name: Detect Breaking Changes
    runs-on: ubuntu-latest
    needs: breaking-changes-manifest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download manifest
        uses: actions/download-artifact@v4
        with:
          name: breaking-changes-manifest
      - name: Run breaking changes validator
        run: |
          set -e
          go run ./tools/cmd/breakvalidator generate > changed.json
          go run ./tools/cmd/breakvalidator validate -m main.json -c changed.json
