# synced from apix-actions/.github/workflows/create-jira.yaml
name: Create Jira Ticket

on:
  pull_request:
    types: [labeled]

permissions: {}

jobs:
  create-jira:
    if: github.event.label.name == 'create_jira'
    uses: mongodb/apix-action/.github/workflows/_create-jira.yaml@main
    secrets: inherit