# synced from apix-actions/.github/workflows/create-jira.yaml
name: Create Jira Ticket

on:
  pull_request:
    types: [labeled]

permissions: {}

jobs:
  create-jira:
    if: github.event.label.name == 'create_jira'
    permissions:
      contents: read
      pull-requests: write
    uses: mongodb/apix-action/.github/workflows/_create-jira.yaml@ef5a3322db780b664092ae80ac06b710ec1bb1de # main
    secrets: inherit