---
  name: Create JIRA ticket for dependabot prs

  on:
    pull_request:
      types: [opened]

  permissions: 
    pull-requests: write
    contents: read
  jobs:
    jira_task:
      name: Create Jira issue
      runs-on: ubuntu-latest
      if: github.actor == 'dependabot[bot]'
      steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: Create JIRA ticket
        id: create
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          json_response=$(curl --request POST \
            --url 'https://jira.mongodb.org/rest/api/2/issue' \
            --header 'Authorization: Bearer '"${JIRA_API_TOKEN}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "fields": {
                  "project": {
                      "id": "10984"
                  },
                  "summary": "MongoCLI Dependency Update n. '"${PR_NUMBER}"'",
                  "issuetype": {
                      "id": "12"
                  },
                  "customfield_12751": [{
                          "id": 27065"
                  }],
                  "description": "This ticket tracks the following GitHub pull request: '"${PR_URL}"'.",
                  "components": [
                      {
                          "id": "28030"
                      }
                  ],
              }
            }')
  
          echo "Response: ${json_response}"
  
          JIRA_TICKET_ID=$(echo "${json_response}" | jq -r '.key')
  
          echo "The following JIRA ticket has been created: ${JIRA_TICKET_ID}"
          echo "jira-ticket-id=${JIRA_TICKET_ID}" >> "${GITHUB_OUTPUT}"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The ticket [${{ steps.create.outputs.jira-ticket-id }}](https://jira.mongodb.org/browse/${{ steps.create.outputs.jira-ticket-id }}) was created for internal tracking.
