name: Build CLI Docker image

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  verify_image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Linting
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Build Image
        run: docker buildx build --no-cache -t atlas .
