name: Build CLI Docker image

on:
  push:
    paths:
      - './Dockerfile'

jobs:
  verify_image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build Image
        run: docker build --no-cache -t atlas .