name: Docs Team Notification
on:
  pull_request:
    types:
      - review_requested
jobs:
  slack-notification-doc-team:
    name: Notify Docs Team on Slack
    runs-on: ubuntu-latest
    if: github.event.requested_team.slug == 'docs-cloud-team'
    permissions:
      pull-requests: write # Needed by sticky-pull-request-comment
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88
        id: append_comment
        with:
          header: pr-title-slack-doc
          message: "APIx Bot :bowtie:: a message has been sent to Docs Slack channel :rocket:."
      - uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d
        if: steps.append_comment.outputs.previous_comment_id == ''
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_DOCS }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "hey ${{ secrets.SLACK_DOCS_TAG }}, this is APIx Bot :aileafy:, could you please review <${{ github.event.pull_request.html_url }}|PR ${{ github.event.pull_request.number }}> :pretty-please:? thanks a lot!"
                  }
                }
              ]
            }
