name: Augment SBOM

on:
  workflow_dispatch:

jobs:
  echo-secret:
    name: Echo ASSIGNEE_JIRA_TICKET
    runs-on: ubuntu-latest
    steps:
      - name: Write ASSIGNEE_JIRA_TICKET to file
        env:
          ASSIGNEE_JIRA_TICKET: ${{ secrets.ASSIGNEE_JIRA_TICKET }}
        run: |
          echo -n "$ASSIGNEE_JIRA_TICKET" > assignee_jira_ticket.txt
      - name: Upload ASSIGNEE_JIRA_TICKET file
        uses: actions/upload-artifact@v4
        with:
          name: assignee-jira-ticket
          path: assignee_jira_ticket.txt
