name: Issue and PRs Labeler
on:
  issues:
    types: [opened, edited]
jobs:
  labeler:
    name: Add Label to PRs and Issues
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Needed by labeler
      issues: write # Needed by labeler
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Add Labels
        uses: srvaroa/labeler@bf262763a8a8e191f5847873aecc0f29df84f957
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config_path: .github/labeler.yaml
          use_local_config: true
