---
name: Library owners check
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        golang: [1.19]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
      - name: Run check-library-owners
        run: make check-library-owners
