---
name: Library owners check
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  libraryOwners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run check-library-owners
        run: make check-library-owners
