---
name: Library owners check
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  libraryOwners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: Linux-go-1.19-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            Linux-go-1.19-
      - name: Run check-library-owners
        run: make check-library-owners
