---
name: Test Andrea Action
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: andreaangiolillo/atlasCLI-gitHub-action@v0.0.2
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash