name: Update Compliance Report

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'atlascli tag version (e.g. 1.42.2)'
        required: true
        type: string

jobs:
  update-compliance-report:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract AUTHOR and VERSION
        id: extract
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            # Expect input like 'atlascli/v1.42.2' or '1.42.2'
            TAG="${{ github.event.inputs.tag }}"
            VERSION="${TAG#atlascli/v}"
            AUTHOR="${{ github.actor }}"
          else
            # GITHUB_REF is refs/tags/atlascli/v1.42.2
            VERSION="${GITHUB_REF#refs/tags/atlascli/v}"
            AUTHOR="${{ github.event.release.author.login }}"
          fi
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Run gen-ssdlc-report.sh
        env:
          AUTHOR: ${{ steps.extract.outputs.author }}
          VERSION: ${{ steps.extract.outputs.version }}
        run: ./build/package/gen-ssdlc-report.sh
      - name: set Apix Bot token
        id: app-token
        uses: mongodb/apix-action/token@3024080388613583e3bd119bfb1ab4b4dbf43c42
        with:
          app-id: ${{ secrets.APIXBOT_APP_ID }}
          private-key: ${{ secrets.APIXBOT_APP_PEM }}
      - uses: peter-evans/create-pull-request@v6
        id: pr
        with:
          token: ${{ steps.app-token.outputs.token }}
          committer: "${{ steps.app-token.outputs.user-name }} <${{ steps.app-token.outputs.user-email }}>"
          author: "${{ steps.app-token.outputs.user-name }} <${{ steps.app-token.outputs.user-email }}>"
          title: "chore: update compliance report for v${{ steps.extract.outputs.version }}"
          commit-message: "chore: update compliance report for v${{ steps.extract.outputs.version }}"
          delete-branch: true
          base: main
          branch: update-compliance-report-v${{ steps.extract.outputs.version }}
          labels: |
            compliance
            auto
          body: |
            ## Proposed changes
            Update compliance report for v${{ steps.extract.outputs.version }}

      - name: Set auto merge
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge "${{ steps.pr.outputs.pull-request-url }}" --auto --squash
